version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.15.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run test

workflows:
  version: 2
  test-workflow:
    jobs :
      - test
