#!/usr/bin/env bash

set -eu

SCRIPT_DIR=$(cd $(dirname $0); pwd)

DOUSI_TEMP=`mktemp`

genarate_json(){
  local TEMP=`mktemp`

  ## remove near distance words
  cat "$1" |
  grep -v -f ${SCRIPT_DIR}/spell_NG_word.txt |
  xargs -L1 -I@ bash -c "mecab ${1}|cut -d, -f8| agrep -c -1 '@';echo @" 2>/dev/null |
  xargs -L2 |
  sort -nrs -k1,1 > "$TEMP"

  ## remove partial match
  cat "$TEMP" |
  cut -d' ' -f2-|
  xargs -L1 -I@ bash -c "grep '@' '${TEMP}'|wc -l;echo @"|
  xargs -L2 |
  awk '$1==1{print $2}'|

  ## genarate json
  head -256|
  paste <((seq 32 255;seq 0 31)|xargs -L1 -I@ bash -c 'echo 0$(echo "obase=16;@"|bc)|grep -o "..$"') - |
  sort -k1,1 |
  sed -r 's/^(.*)\t/  \"\1\":/;s/:(.*)/: ["\1"],/'|
  sed '1s/^/{\n/;256s/,/\n}/'
}

MEISI_TEMP=`${SCRIPT_DIR}/meisi_json_generator | sed -n 2p`

cat ${SCRIPT_DIR}/spell.txt |
base64 -d |
mecab |
tr '\t' ,|
awk -F, '$2~/動詞/&&$2!~/助動詞/{print $1}'|
sort -u |
sed -n '/../p'|
grep -P '\p{Han}' |
grep -v -f <(cat "$MEISI_TEMP" | cut -d'"' -f 4)  > "$DOUSI_TEMP"


genarate_json $DOUSI_TEMP |
sed 's/"/。"/4' |
sed '/0A/s/\[.*]/["具現化せよ。", "踊れ。", "歌え。", "紡げ。"]/' > ${SCRIPT_DIR}/../data/dousi.json
