#!/usr/bin/env bash

set -eu

SCRIPT_DIR=$(cd $(dirname $0); pwd)

MEISI_TEMP=`mktemp`

## 名詞と副詞と連体化した単語を合わせたテキストの生成
cat ${SCRIPT_DIR}/spell.txt |
base64 -d |
mecab |
tr '\t' ,|
awk -F, '$2~/名詞/|| $1~/EOF/{print s;a=1;s=$1}a==2{a=0;s=""}a==1&&$2~/助詞/{a=0;if($3~/連体化/){a=2}s=s$1}'|
sort -u |
sed -n '/../p'|
grep -P '\p{Han}' > "$MEISI_TEMP"

## 部分一致指定舞う単語の排除
MEISI_UNIQ_TEMP=`mktemp`
cat "$MEISI_TEMP" |
xargs -L1 -I@ bash -c "echo \$(grep -c @ $MEISI_TEMP) @"|
awk '$1==1{print $2}'|
## NG単語の排除
grep -v -f $SCRIPT_DIR/spell_NG_word.txt |
cat > $MEISI_UNIQ_TEMP

## 同じ漢字で始まる単語をグルーピング
MEISI_RESULT_TEMP=`mktemp`
cat $MEISI_TEMP |
grep -oP '^\p{Han}'|
sort -u |
xargs -L1 -I@ bash -c "grep '^@' $MEISI_UNIQ_TEMP |xargs"|
sort -u|
awk '{print NF,$0}'|
sort -nr -k1,1|
head -256|
cut -d' ' -f2- > $MEISI_RESULT_TEMP

## genarate json
cat $MEISI_RESULT_TEMP|
head -256|
paste <((echo 10;seq 32 255;seq 0 31|grep -v 10)| xargs -L1 -I@ bash -c 'echo 0$(echo "obase=16;@"|bc)|grep -o "..$"') - |
sort -k1,1 |
sed 's/ /","/g' |
sed -r 's/^(.*)\t/  \"\1\":/;s/:(.*)/: ["\1"],/'|
sed '1s/^/{\n/;$s/,$/\n}/' > ${SCRIPT_DIR}/../data/meisi.json

## DEBUG用？
echo $MEISI_TEMP
echo $MEISI_UNIQ_TEMP
echo $MEISI_RESULT_TEMP
