#!/usr/bin/env bash

set -eu

MEISI_TEMP=`mktemp`
DOUSI_TEMP=`mktemp`

genarate_json(){
  ## remove near distance words
  cat "$1" |
  grep -v -f spell_NG_word.txt |
  xargs -L1 -I@ bash -c "agrep '@' ${1}|wc -l;echo @" 2>/dev/null |
  xargs -L2 |
  sort -nrs -k1,1 |

  ## genarate json
  cut -d' ' -f2-|
  head -256|
  paste <((seq 32 255;seq 0 31)|xargs -L1 -I@ bash -c 'echo 0$(echo "obase=16;@"|bc)|grep -o "..$"') - |
  sort -k1,1 |
  sed -r 's/^(.*)\t/\"\1\":/;s/:(.*)/:"\1",/'|
  sed '1s/^/{\n/;256s/,/\n}/'
}

cat spell.txt |
mecab |
tr '\t' ,|
awk -F, '$2~/名詞/|| $1~/EOF/{print s;a=1;s=$1}a==2{a=0;s=""}a==1&&$2~/助詞/{a=0;if($3~/連体化/){a=2}s=s$1}'|
sort -u |
sed -n '/../p'|
grep -P '\p{Han}' > "$MEISI_TEMP"


cat spell.txt |
mecab |
tr '\t' ,|
awk -F, '$2~/動詞/|| $1~/EOF/{print s;a=1;s=$1}a==2{a=0;s=""}a==1&&$2~/助詞/{a=0;if($3~/連体化/){a=2}s=s$1}'|
sort -u |
sed -n '/../p'|
grep -P '\p{Han}' > "$DOUSI_TEMP"


genarate_json $MEISI_TEMP > ../meisi.json
genarate_json $DOUSI_TEMP | 
sed '/0A/s/"[^"]*/"命ず/3' > ../dousi.json
